### ISSUE TITLE
[JOSS Review] Vignette

### ISSUE THREAD

**Issue by gvegayon** [JonasMoss/kdensity#50]
Part of JOSS review openjournals/joss-reviews#1566

This is more a question than anything, how this statement is true? 

https://github.com/JonasMoss/kdensity/blob/ade1d128517b106364a071b29e85af4e0aee8e44/vignettes/tutorial.Rmd#L137 

I mean, I was expecting to see a big difference (improvement) on the curve fitting in order to say that, but it seems that the normal kd is doing a fair job (perhaps better?). This from the fact that I'm not an expert in parametric/nonparametric kernel models. It would be nice to have a better explanation of this in the vignette :).

**Comment by JonasMoss** [comment]
Made a change in e5148f40275f3799b6fe26f7ea66706e78b235ee. My only point is that you don't appear to need KDE in order to have a good fit to the density. Since KDEs are more complex and parametric densities, I think it's better to use parametrics when you can.

So no hidden expertise in non-parametric models involved here, sadly. :p
