### ISSUE TITLE
Slow performance of beta distribution

### ISSUE THREAD

**Issue by pkumar81** [JonasMoss/kdensity#65]
The runtime with the beta kernel appears to be too slow to be practical. On only 1000 points it takes more than 10 seconds on a high-performance server, then for 2000 over a minute, and when you get to over 10000 points, it can run more than an hour. Is there any way to speed this up? Here is a sample command on 2000 uniformly distributed points that takes typically over a minute to run:

` system.time(tmp<-kdensity(runif(2000), support = c(0,1), kernel = "beta"))`

Are you aware of any other implementation of Chen(1999) beta kernel smoothing?

Thank you.

**Comment by JonasMoss** [comment]
I think the problem is the bandwidth selection procedure, which defaults tocross-validation, which is the bottleneck. Chen (and others) probably made smarter bandwidth selectors, but we haven't implemented them.

On the other hand, do you have yo use beta kernels? The "gcopula" (Jones, Henderson, 2007) kernel (in this package) is much faster, as we used its own, custom-made bandwidth selector. I don't think the beta kernels perform that much better, if at all, than the "gcopula" kernels, which have their own benefits (being bona fide densities is one of them.) 

Finally, packages such as https://cran.r-project.org/web/packages/logKDE/index.html are specifically designed for speed. It uses the log-transform, but there are density estimators on [0,1] using e.g. the probit transform, as Geenes (2014).

Jones, M. C., & Henderson, D. A. (2007). Kernel-Type Density Estimation on the Unit Interval. Biometrika, 94(4), 977–984. https://doi.org/10.1093/biomet/asm068

Geenens, G. (2014). Probit Transformation for Kernel Density Estimation on the Unit Interval. *Journal of the American Statistical Association*, *109*(505), 346–358. https://doi.org/10.1080/01621459.2013.842173
